### ISSUE TITLE
a small mistake of spelling in your axiv paper

### ISSUE THREAD

**Issue by ChristopheZhao** [xxxiaol/QRData#1]
Hi, your work exploring the causal reasoning ability of LLM is interesting. I found a small mistake in the annotation of table 4. It would be clearer if you could correct it.
![image](https://github.com/xxxiaol/QRData/assets/17317538/3bb547da-0e92-4bb0-8188-afcb1d09ef83)

**Comment by xxxiaol** [comment]
Thank you for your careful reading! We will fix it in the future version.
